CREATE DATABASE IF NOT EXISTS projeto1
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE projeto1;

CREATE TABLE clientes (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cliente VARCHAR(150) NOT NULL,
  cidade VARCHAR(100) DEFAULT NULL,
  estado VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE paginas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  produto TEXT NOT NULL,
  descricao VARCHAR(100) DEFAULT NULL,
  preco INT(11) NOT NULL,
  texto TEXT DEFAULT NULL,
  imagem VARCHAR(500) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;